repos:
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: python -m nbconvert --ClearOutputPreprocessor.enabled=True --inplace
      - id: pylint
        alias: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
      - id: black
        alias: black
        name: black
        entry: black
        language: system
        types: [python]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
    - id: check-ast